
name: CI

on:
  push:
    paths:
      - 'watsrc/*'
      - 'tssrc/*'
      - 'tests/*'
      - 'tsconfig.json'
      - '.github/workflows/*'
  pull_request:
    paths:
      - 'watsrc/*'
      - 'tssrc/*'
      - 'tests/*'
      - 'tsconfig.json'
      - '.github/workflows/*'

jobs:
  test-wasm:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Test Environment
        run: |
          sudo apt-get update --upgrade
          sudo apt-get install -y wabt
      
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npm i
      # - name: Fetch Repository
      #   uses: actions/checkout@v4

      - name: Compile and Test
        run: |
          nvm install 18.0.0
          nvm use 18.0.0 && npm install
          npm run compile
          wat2wasm watsrc/*.wat -o watsrc/novice.wasm
          npm run coverage

